name: Generate Sitemap

on:
  push:
    branches: [main]
    paths: ["**.html"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Generate a sitemap
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate Sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1.10.3
        with:
          base-url-path: https://chandujr.github.io/kannada-varnamale/

      - name: Commit sitemap
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sitemap.xml
          git commit -m "Update sitemap.xml" || echo "No changes to commit"
          git push
